version: '3.1'
services:
  web:
    image: la289/iotdashboard:go-iotdashboard
    restart: always
    expose:
      - 8080
      - 9090
    ports:
      - 8080:8080
      - 9090:9090
    links:
      - db
  db:
    image: "postgres"
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iot_dashboard
